[package]
name = "roman-numeral"
version = "0.1.0"
authors = ["Emil Gardström <emil.gardstrom@gmail.com>"]

[dependencies]
num = "*"
num-derive = "*"
itertools = "*"
clippy = {version = "*", optional = true}
