[package]
name = "lang-interp"
version = "0.7.0"
authors = ["Emil Gardström <emil.gardstrom@gmail.com>"]

[dependencies]
clap = "*"
serde = "*"
serde_derive = "*"
serde_yaml = "*"

[[bin]]
name = "language-interpretor"
path = "src/main.rs"
