[package]
name = "lang-interp"
version = "0.6.1"
authors = ["Emil Gardström <emil.gardstrom@gmail.com>"]

[dependencies]
clap = "*"
serde = "*"
serde_yaml = "*"
serde_macros = "*"
[[bin]]
name = "language-interpretor"
path = "src/main.rs"
